name: Build LineageOS 21

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk git-core gnupg flex bison gperf build-essential \
          zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
          libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python-is-python3
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=$PATH:~/bin' >> ~/.bashrc
        source ~/.bashrc
        echo "repo version"
        
    - name: Clean up workspace
      run: |
        rm -rf ~/android/lineage
        mkdir -p ~/android/lineage

    - name: Clone LineageOS 21 Source
      run: |
        git clone --depth=1 https://github.com/LineageOS/android.git ~/android/lineage -b lineage-21.0

    - name: Sync Device Repositories
      run: |
        cd ~/android/lineage
        export PATH=$PATH:~/bin  # Ensure repo is in PATH
        repo init -u https://github.com/LineageOS/android.git -b lineage-21.0
        repo sync -c --force-sync --no-tags --no-clone-bundle -j$(nproc)

    - name: Clone Device Repositories
      run: |
        cd ~/android/lineage
        git clone --depth=1 https://${{ secrets.GH_TOKEN }}@github.com/Dan13254/lineage_device_samsung_a22x.git device/samsung/a22x
        git clone --depth=1 https://${{ secrets.GH_TOKEN }}@github.com/Dan13254/android_vendor_samsung_a22x.git vendor/samsung/a22x
        git clone --depth=1 https://${{ secrets.GH_TOKEN }}@github.com/Dan13254/android_kernel_samsung_a226b.git kernel/samsung/a22x

    - name: Build ROM
      run: |
        cd ~/android/lineage
        export PATH=$PATH:~/bin  # Ensure repo is in PATH
        source build/envsetup.sh
        lunch lineage_a22x-userdebug
        make -j$(nproc --all) bacon

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: lineageos
        path: ~/android/lineage/out/target/product/a22x/*.zip
